binary = "./binaries/X86/MODE_32/sshd"
random_seed = 0xf00d

[genome]
mutation_rate = 0.04
min_length = 10
max_length = 500

[geography]
dimensions = [32, 32]
distance = "x -> x^6"
tournament_size = 4
toroidal = true

[fitness]
fitness_function = "./fitness.jl"
