binary = "./binaries/X86/MODE_32/sshd"

[genome]
mutation_rate = 0.04
min_length = 10
max_length = 500

[geography]
dimensions = [32, 32]
distance = "x -> x^6"
tournament_size = 4
fitness_function = "fitness.jl"
toroidal = true